config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'home#index', as: :home
  get '/sign_in', to: 'bot_signin#show'
  post '/sign_in' , to: 'bot_signin#add_bot',as: :add_bot
  get '/clear-token', to: 'home#clear_token', as: :clear_token
  get '/show/:chat_id', to: 'home#show', as: :chat
  post '/send_message/:chat_id' , to: 'home#send_message',as: :send_message


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :chat
end

app/models/offset.rb
class Offset < ApplicationRecord
    validates :bot_id, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protected
    def populate_data
        offset = Offset.find_or_initialize_by(bot_id: session[:bot_id])
        updates = Telegram.bot.get_updates(offset: offset.offset+1)
        max_offset = 0
        if updates["ok"]
            updates["result"].each do |update|
                max_offset = update["update_id"]
                Message.create(message_id: update["message"]["message_id"], date: update["message"]["date"], text: update["message"]["text"], chat_id: update["message"]["chat"]["id"], sender_id: update["message"]["from"]["id"])
                chat = Chat.find_or_initialize_by(id: update["message"]["chat"]["id"])
                chat.first_name = update["message"]["chat"]["first_name"]
                chat.last_name = update["message"]["chat"]["last_name"]
                chat.username = update["message"]["chat"]["username"]
                chat.bot_id = session[:bot_id]
                chat.save
            end
            if offset.offset < max_offset
                offset.offset = max_offset
                offset.save
            end
        else
            puts "you failed"
        end
    end
end

app/controllers/bot_signin_controller.rb
class BotSigninController < ApplicationController
    def show
        @bot = session[:bot_id]
        @bot_username = session[:bot_username]
    end

    def add_bot
        session[:bot_token]=params[:Bot_Token]
        Telegram.bots_config = {
            default: params[:Bot_Token]
          }
        Telegram::Bot::Client.new(params[:Bot_Token])
        resp = Telegram.bot.get_me
        puts resp["result"]["id"]
        resp.each do |key, value|
            puts "#{key}:#{value}"
        end
        if resp["ok"]
            session[:bot_id] = resp["result"]["id"]
            session[:bot_username] = resp["result"]["username"]
            populate_data
            redirect_to '/'
        else
            puts "can't find bot"
            redirect_to '/sign_in'
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :load_entities
    def index
        populate_data
        @bot_id = session[:bot_id]
        @bot_username = session[:bot_username]
        if !@bot_id
            redirect_to sign_in_path
        end
        @chats = Chat.all
    end

    def show
        populate_data
        @bot_username = session[:bot_username]
        @chat = Chat.find(params[:chat_id])
    end

    def clear_token
        @bot_token = session[:bot_token] = nil
        @bot_id = session[:bot_id] = nil
        @bot_username = session[:bot_username] = nil
        Telegram.bots_config = {
            default: nil
          }
        redirect_to '/sign_in'
    end

    def send_message
        puts params
        resp = Telegram.bot.send_message(chat_id: params[:chat_id], text: params[:message_text])
        if resp["ok"]
            Message.create(message_id: resp["result"]["message_id"], date: resp["result"]["date"], text: resp["result"]["text"], chat_id: resp["result"]["chat"]["id"], sender_id: resp["result"]["from"]["id"])
            puts resp.to_yaml
        else
            flash[:danger] = "failed to send message"
        end
        redirect_to chat_path(chat_id: params[:chat_id])
    end

    def load_entities
        populate_data
        @chats = Chat.all
        @chat = Chat.find(params[:id]) if params[:id]
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_url(user)
        gravatar_id = Digest::MD5::hexdigest(user.email).downcase
        url = "https://gravatar.com/avatar/#{gravatar_id}.png"
      end
end

app/helpers/bot_signin_helper.rb
module BotSigninHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bot_signin/show.html.erb
<% if @bot %>
<h3>You already gave us a token please go <%= link_to "home", home_path %> to start messaging </h3>
<% else %>
<%= form_tag(add_bot_path) do %>
    <div class="form-group">
        <label for="Bot_Token">Bot Token</label>
        <%= text_field_tag :Bot_Token, "", class: 'form-control' %>
        <small id="Bot_Token" class="form-text text-muted">We'll never share your token with anyone else.</small>
    </div>

    <div class="actions">
        <%= submit_tag "Submit" %>
    </div>
<% end %>
<% end %>

app/views/home/_chats.html.erb
<div class="mb-3">
        <div class="alert alert-primary">
        <h4 class="alert-heading">
            Chats 
        </h4>
        </div>
    </div>

    <% if @chats.present? %>
      <nav class="nav flex-column">
        <% @chats.each do |chat| %>
          <%= link_to "#{chat.first_name} #{chat.last_name}", chat_path(chat), class: "nav-link chat-nav-link" %>
        <% end %>
      </nav>
    <% else %>
      <div class="text-muted">
        The are no chats
      </div>
    <% end %>

app/views/home/index.html.erb
<div class="row">
  <div class="col-12 col-md-3">
     <%= render partial: 'chats' %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome 
      </h4>


      <hr />

      <p>
        You can check chats from the sidebar.
      </p>
    </div>
</div>

app/views/home/show.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'chats' %>
  </div>

  <div class="col">
    <h1>
        <%= "#{@chat.first_name} #{@chat.last_name}" %>
    </h1>

    <div class="chat">
      <% @chat.messages.each do |chat_message| %>
        <div class="chat-message-container">
          <% if chat_message.sender_id == @chat.bot_id %>
            <div class="row no-gutters">
                <div class="col-5 ml-auto p-2">
                <div class="message-content" style = "background: #3d52c7">
                    <p class="mb-1">
                        <%= chat_message.text %>
                    </p>

                    <div class="text-right">
                    <small>
                        <%= Time.at(chat_message.date.to_i).to_datetime %>
                    </small>
                    </div>
                </div>
                </div>
            </div>
            </div>
          <% else %>
            <div class="row no-gutters">
                <div class="col-5">
                <div class="message-content">
                    <p class="mb-1">
                        <%= chat_message.text %>
                    </p>

                    <div class="text-right">
                    <small>
                        <%= Time.at(chat_message.date.to_i).to_datetime %>
                    </small>
                    </div>
                </div>
                </div>
            </div>
            </div>
          <% end %>
      <% end %>
    </div>
    <%= form_tag(send_message_path(@chat.id)) do %>
      <div class="input-group">
        <%= text_field_tag :message_text, "", class: 'chat-input' %>
        <div class="input-group-append">
          <%= submit_tag "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsChatTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render partial: 'shared/navigation_bar' , locals: { bot: @bot_username } %>
          <div class="my-3">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" href="/">Octopods telegram chat</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if @bot_username %>
    <%= link_to "#{@bot_username} logout", clear_token_path(), method: :get %>
  <% end %>
</nav>